services:
  yamtrack:
    container_name: "yamtrack"
    image: "ghcr.io/fuzzygrim/yamtrack"
    restart: "unless-stopped"
    depends_on:
      - "redis"
    environment:
      TZ: "${TZ:-Etc/UTC}"
      # Generate a random value securely:
      #     $ docker run --rm --entrypoint "python" ghcr.io/fuzzygrim/yamtrack -c "\
      #     from django.core.management.utils import get_random_secret_key; \
      #     print(get_random_secret_key())"
      SECRET: "${SECRET:?Must set to secure random string!}"
      REDIS_URL: "redis://redis:6379"
    volumes:
      - "./db:/yamtrack/db"
    ports:
      - "${LAN_IP:-127.0.0.1}:8000:8000"

  redis:
    container_name: "yamtrack-redis"
    image: "redis:8-alpine"
    restart: "unless-stopped"
    volumes:
      - "redis_data:/data"

volumes:
  redis_data:
